spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb4
    username: barskovpavelev
    password: 1234