spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
          hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb4
    username: tom
    password: tomabcbcbc